#!/usr/bin/env python3
"""Migrate a legacy Research Mission without inheriting unverified claims.

The 1.0 mission format allowed loose artifact records.  Migration to 1.1 is
therefore deliberately trust-reducing: a legacy ``validated`` label, checksum,
or validation object is retained only as inert audit history.  No artifact file
is opened and no checksum is generated by this module.
"""

from __future__ import annotations

import argparse
import copy
import json
import re
import sys
from datetime import datetime
from pathlib import Path
from typing import Any


SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from director_common import load_document, write_document  # noqa: E402


SOURCE_VERSION = "1.0"
TARGET_VERSION = "1.1"
ARTIFACT_ENVELOPE_VERSION = "1.0"
LOCATOR_FIELDS = ("path", "uri", "content_ref")
ACTIVE_VALIDATION_FIELDS = (
    "content_sha256",
    "validation",
    "validated_at",
    "validation_status",
    "validator",
)
VERSION_PATTERN = re.compile(r"^(\d+)\.(\d+)$")


class MigrationError(ValueError):
    """Raised when a mission cannot be safely migrated."""


def _parse_version(value: Any) -> tuple[int, int]:
    if not isinstance(value, str) or not VERSION_PATTERN.fullmatch(value):
        raise MigrationError("mission schema_version must use major.minor form")
    match = VERSION_PATTERN.fullmatch(value)
    assert match is not None
    return int(match.group(1)), int(match.group(2))


def _migration_timestamp(value: Any) -> str:
    if not isinstance(value, str) or not value.strip():
        raise MigrationError("migrated_at must be supplied explicitly")
    candidate = value.strip().replace("Z", "+00:00")
    try:
        parsed = datetime.fromisoformat(candidate)
    except ValueError as error:
        raise MigrationError("migrated_at must be a valid ISO-8601 timestamp") from error
    if parsed.tzinfo is None or parsed.utcoffset() is None:
        raise MigrationError("migrated_at must include a UTC offset")
    return parsed.isoformat()


def _valid_timestamp(value: Any) -> bool:
    if not isinstance(value, str) or not value.strip():
        return False
    try:
        parsed = datetime.fromisoformat(value.strip().replace("Z", "+00:00"))
    except ValueError:
        return False
    return parsed.tzinfo is not None and parsed.utcoffset() is not None


def _nonempty(value: Any) -> bool:
    return isinstance(value, str) and bool(value.strip())


def _artifact_identifier(artifact: dict[str, Any], index: int) -> str:
    value = artifact.get("artifact_id")
    return value.strip() if _nonempty(value) else f"artifacts[{index}]"


def _legacy_validation_record(
    artifact: dict[str, Any], previous_status: Any, migrated_at: str
) -> dict[str, Any] | None:
    prior = artifact.get("legacy_validation")
    record = copy.deepcopy(prior) if isinstance(prior, dict) else {}
    # Even an already-labelled legacy record is historical evidence only.  Do
    # not allow an old ``effective: true`` flag to survive the trust boundary.
    captured = bool(record)
    if previous_status == "validated":
        record["previous_status"] = "validated"
        captured = True
    for field in ACTIVE_VALIDATION_FIELDS:
        if field in artifact:
            record[field] = copy.deepcopy(artifact.pop(field))
            captured = True
    if not captured:
        return None
    record.update(
        {
            "effective": False,
            "migrated_at": migrated_at,
            "reason": (
                "Legacy validation was not content-bound under the 1.1 contract and "
                "must not satisfy an active artifact or release gate."
            ),
        }
    )
    return record


def _migrate_artifact(
    raw_artifact: Any,
    *,
    index: int,
    mission_id: Any,
    migrated_at: str,
    report: dict[str, Any],
) -> Any:
    if not isinstance(raw_artifact, dict):
        report["warnings"].append(f"artifacts[{index}] is not an object and was preserved unchanged")
        return copy.deepcopy(raw_artifact)

    artifact = copy.deepcopy(raw_artifact)
    artifact_id = _artifact_identifier(artifact, index)
    envelope_version = artifact.get("schema_version")
    if envelope_version not in (None, ARTIFACT_ENVELOPE_VERSION):
        raise MigrationError(
            f"artifact {artifact_id} declares unsupported envelope version {envelope_version!r}"
        )
    artifact["schema_version"] = ARTIFACT_ENVELOPE_VERSION

    previous_status = artifact.get("status")
    legacy_validation = _legacy_validation_record(artifact, previous_status, migrated_at)
    if legacy_validation is not None:
        artifact["legacy_validation"] = legacy_validation
        report["legacy_validation_artifacts"].append(artifact_id)
    if previous_status == "validated":
        report["downgraded_validated_artifacts"].append(artifact_id)

    has_locator = any(_nonempty(artifact.get(field)) for field in LOCATOR_FIELDS)
    artifact["status"] = "created" if has_locator else "planned"
    report["created_artifacts" if has_locator else "planned_artifacts"].append(artifact_id)

    provenance_value = artifact.get("provenance")
    provenance = copy.deepcopy(provenance_value) if isinstance(provenance_value, dict) else {}
    migration_metadata = provenance.get("migration")
    migration_metadata = copy.deepcopy(migration_metadata) if isinstance(migration_metadata, dict) else {}
    migration_metadata.update(
        {
            "from_mission_schema_version": SOURCE_VERSION,
            "migrated_at": migrated_at,
            "trust": "unverified_legacy_metadata",
            "previous_status": previous_status,
        }
    )
    if provenance_value not in (None, {}) and not isinstance(provenance_value, dict):
        migration_metadata["legacy_provenance"] = copy.deepcopy(provenance_value)
    if not _nonempty(provenance.get("mission_id")) and _nonempty(mission_id):
        provenance["mission_id"] = mission_id
    elif _nonempty(provenance.get("mission_id")) and provenance.get("mission_id") != mission_id:
        report["warnings"].append(
            f"artifact {artifact_id} provenance mission_id differs from the parent mission"
        )
    if not _nonempty(provenance.get("producer")):
        # This sentinel is intentionally not a trusted producer.  A later human
        # repair must identify the actual producer before the artifact can pass
        # the shared artifact contract.
        provenance["producer"] = "legacy_unknown"
        migration_metadata["producer_status"] = "not_recorded"
        report["unresolved_provenance_artifacts"].append(artifact_id)
    provenance["migration"] = migration_metadata
    artifact["provenance"] = provenance

    if not _valid_timestamp(artifact.get("created_at")):
        previous_created_at = artifact.get("created_at")
        artifact["created_at"] = migrated_at
        migration_metadata["created_at_source"] = "migration_timestamp_fallback"
        if previous_created_at not in (None, ""):
            migration_metadata["legacy_created_at"] = copy.deepcopy(previous_created_at)
            report["warnings"].append(
                f"artifact {artifact_id} had an invalid created_at and now uses migrated_at"
            )

    return artifact


def _migrate_route_step(raw_step: Any, index: int, report: dict[str, Any]) -> Any:
    if not isinstance(raw_step, dict):
        report["warnings"].append(f"route[{index}] is not an object and was preserved unchanged")
        return copy.deepcopy(raw_step)
    step = copy.deepcopy(raw_step)
    changed = False
    expected = step.get("expected_outputs")
    expected = copy.deepcopy(expected) if isinstance(expected, list) else []
    if not isinstance(step.get("required_output_groups"), list):
        step["required_output_groups"] = [expected] if expected else []
        changed = True
    if not isinstance(step.get("optional_outputs"), list):
        required_members = {
            json.dumps(item, ensure_ascii=False, sort_keys=True)
            for group in step["required_output_groups"]
            if isinstance(group, list)
            for item in group
        }
        step["optional_outputs"] = [
            item
            for item in expected
            if json.dumps(item, ensure_ascii=False, sort_keys=True) not in required_members
        ]
        changed = True
    if changed:
        report["route_steps_updated"].append(step.get("step_id") or f"route[{index}]")
    return step


def migrate_mission(mission: Any, *, migrated_at: str) -> dict[str, Any]:
    """Return ``mission`` and an audit report for an explicit 1.0 -> 1.1 migration."""

    timestamp = _migration_timestamp(migrated_at)
    if not isinstance(mission, dict):
        raise MigrationError("mission root must be an object")
    current_version = mission.get("schema_version")
    current = _parse_version(current_version)
    target = _parse_version(TARGET_VERSION)
    if current > target:
        raise MigrationError(
            f"mission schema_version {current_version} is newer than supported {TARGET_VERSION}"
        )
    if current_version == TARGET_VERSION:
        return {
            "mission": copy.deepcopy(mission),
            "report": {
                "from_version": TARGET_VERSION,
                "to_version": TARGET_VERSION,
                "migrated_at": timestamp,
                "changed": False,
                "status": "already_current",
                "artifact_count": len(mission.get("artifacts", []))
                if isinstance(mission.get("artifacts"), list)
                else 0,
                "route_step_count": len(mission.get("route", []))
                if isinstance(mission.get("route"), list)
                else 0,
                "downgraded_validated_artifacts": [],
                "legacy_validation_artifacts": [],
                "created_artifacts": [],
                "planned_artifacts": [],
                "unresolved_provenance_artifacts": [],
                "route_steps_updated": [],
                "warnings": [],
            },
        }
    if current_version != SOURCE_VERSION:
        raise MigrationError(
            f"unsupported source schema_version {current_version}; expected {SOURCE_VERSION}"
        )

    migrated = copy.deepcopy(mission)
    report: dict[str, Any] = {
        "from_version": SOURCE_VERSION,
        "to_version": TARGET_VERSION,
        "migrated_at": timestamp,
        "changed": True,
        "status": "migrated",
        "artifact_count": 0,
        "route_step_count": 0,
        "downgraded_validated_artifacts": [],
        "legacy_validation_artifacts": [],
        "created_artifacts": [],
        "planned_artifacts": [],
        "unresolved_provenance_artifacts": [],
        "route_steps_updated": [],
        "warnings": [],
    }

    artifacts = mission.get("artifacts", [])
    if not isinstance(artifacts, list):
        report["warnings"].append("artifacts was not a list and was replaced with an empty list")
        artifacts = []
    migrated["artifacts"] = [
        _migrate_artifact(
            artifact,
            index=index,
            mission_id=mission.get("mission_id"),
            migrated_at=timestamp,
            report=report,
        )
        for index, artifact in enumerate(artifacts)
    ]
    report["artifact_count"] = len(artifacts)

    route = mission.get("route", [])
    if not isinstance(route, list):
        report["warnings"].append("route was not a list and was replaced with an empty list")
        route = []
    migrated["route"] = [
        _migrate_route_step(step, index, report) for index, step in enumerate(route)
    ]
    report["route_step_count"] = len(route)

    migrated["schema_version"] = TARGET_VERSION
    history = migrated.get("migration_history")
    history = copy.deepcopy(history) if isinstance(history, list) else []
    history.append(
        {
            "from_version": SOURCE_VERSION,
            "to_version": TARGET_VERSION,
            "migrated_at": timestamp,
            "trust_policy": "legacy validation downgraded; no files opened or hashes generated",
        }
    )
    migrated["migration_history"] = history
    return {"mission": migrated, "report": report}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--migrated-at", required=True)
    parser.add_argument("--report", type=Path)
    args = parser.parse_args()
    try:
        result = migrate_mission(load_document(args.input), migrated_at=args.migrated_at)
        write_document(args.output, result["mission"])
        if args.report:
            write_document(args.report, result["report"])
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(json.dumps({"status": "error", "error": str(error)}, ensure_ascii=False, indent=2))
        return 1
    print(json.dumps(result["report"], ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
